export const CHECKBOOK_CHECKING_BEGIN = 'CHECKBOOK_CHECKING_BEGIN';
export const CHECKBOOK_CHECKING_SUCCESS = 'CHECKBOOK_CHECKING_SUCCESS';
export const CHECKBOOK_CHECKING_FAILURE = 'CHECKBOOK_CHECKING_FAILURE';
export const CHECKBOOK_CHECKING_DISMISS_ERROR = 'CHECKBOOK_CHECKING_DISMISS_ERROR';
