export const DOCUMENTS_HANDLE_SELECTED_FILE = 'DOCUMENTS_HANDLE_SELECTED_FILE';
export const DOCUMENTS_SHOW_DOCUMENT_MODAL = 'DOCUMENTS_SHOW_DOCUMENT_MODAL';
export const DOCUMENTS_HIDE_DOCUMENT_MODAL = 'DOCUMENTS_HIDE_DOCUMENT_MODAL';
